#!/bin/bash

: "${GRADLE_IMAGE:=gradle:6.7.1}"

if ! docker pull --quiet "${GRADLE_IMAGE}" >/dev/null; then
    echo "ERROR: Unable to pull ${GRADLE_IMAGE}."
    exit 1
fi

docker run --interactive --tty \
    --mount "type=bind,src=${HOME},dst=${HOME}" \
    --mount "type=bind,src=${PWD},dst=${PWD}" \
    --user "$(id-u):$(id -g)" \
    --workdir "${PWD}" \
    "${GRADLE_IMAGE}" "$@"