#!/bin/bash

: "${DOTNET_IMAGE:=mcr.microsoft.com/dotnet/sdk:5.0}"

MOUNTS=( "${HOME}" )
if test "${PWD:0:${#HOME}}" != "${HOME}"; then
    MOUNTS+=( "${PWD}" )
fi
for mount in ${DOTNET_ADDITIONAL_MOUNTS}; do
    MOUNTS+=( "${mount}" )
done

if test -n "${DOTNET_NO_MOUNTS}"; then
    MOUNTS=()
fi

MOUNT_PARAMETERS=""
for mount in ${MOUNTS[@]}; do
    if ! test -d "${mount}"; then
        echo "ERROR: Mount path <${mount}> does not exist."
        exit 1
    fi
    MOUNT_PARAMETERS="${MOUNT_PARAMETERS} --mount type=bind,src=${mount},dst=${mount}"
done

if ! docker pull --quiet "${DOTNET_IMAGE}" >/dev/null; then
    echo "ERROR: Unable to pull ${DOTNET_IMAGE}."
    exit 1
fi

COMMAND="$(basename "$0")"

docker run --interactive --tty \
    ${MOUNT_PARAMETERS} \
    --user "$(id -u):$(id -g)" \
    --env HOME=${HOME} \
    --workdir "${PWD}" \
    "${DOTNET_IMAGE}" "${COMMAND}" "$@"
